[package]
name = "powers"
version = "2.1.0"
authors = ["Ruby <ruby@rubidium.dev>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
chrono = "0.2.16"
md5 = "0.7.0"
num_enum = "0.4.2"
serde = { version = "1.0.4", features = ["serde_derive"] }
serde_json = "1.0.48"
toml = "0.5.6"
